### ISSUE TITLE
Docker folder does not exist

### ISSUE THREAD

**Issue by davidlj95** [jpochyla/blockbook#2]
[`README.md`](https://github.com/jpochyla/blockbook/blob/master/README.md) mentions we can install blockbook using Docker:
> ## Install using Docker:
> 
> ```
> git clone https://github.com/jpochyla/blockbook.git
> cd blockbook/docker
> ./build.sh
> ```

But there is no `docker` folder inside the repository, so you can't `cd` into it and therefore can't find `build.sh`

**Comment by martinboehm** [comment]
I updated the README. However, as the product is still in development, do not expect much from it.
